# Generated by Django 5.2.3 on 2025-07-13 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0002_alumno'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='materia',
            field=models.ManyToManyField(to='AppCoder.curso'),
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('apellido', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=254)),
                ('dni', models.IntegerField()),
                ('materia', models.ManyToManyField(to='AppCoder.curso')),
            ],
        ),
    ]
