# Generated by Django 5.2.3 on 2025-07-13 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0003_alumno_materia_profesor'),
    ]

    operations = [
        migrations.AddField(
            model_name='profesor',
            name='profesion',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
